repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.5
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/facebook/pyre-check
    rev: v0.9.25
    hooks:
      - id: pyre-check-no-python
        stages: [pre-push]
